// <auto-generated />
using System;
using GrcPlatform.AssetInventory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GrcPlatform.AssetInventory.Infrastructure.Migrations;

[DbContext(typeof(AssetDbContext))]
[Migration("20260317000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("GrcPlatform.AssetInventory.Domain.Asset", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<string>("Description").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("RiskRating").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
            b.Property<string>("OwnerUserId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("CustodianUserId").HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("CreatedByUserId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("Location").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("SerialNumber").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Manufacturer").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Model").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Version").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("LinkedControlId").HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTimeOffset?>("PurchaseDate").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("ExpiryDate").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("RetiredAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset");
            b.HasKey("Id");
            b.HasIndex("Type");
            b.HasIndex("Status");
            b.HasIndex("RiskRating");
            b.HasIndex("OwnerUserId");
            b.ToTable("Assets");
        });
#pragma warning restore 612, 618
    }
}
