// <auto-generated />
using System;
using GrcPlatform.StatementOfApplicability.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrcPlatform.StatementOfApplicability.Infrastructure.Migrations
{
    [DbContext(typeof(SoaDbContext))]
    partial class SoaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrcPlatform.StatementOfApplicability.Domain.Entities.AnnexAControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Applicability")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ControlId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ControlName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<string>("EvidenceReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImplementationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ImplementationStatus")
                        .HasColumnType("int");

                    b.Property<string>("JustificationForExclusion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ResponsibleOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Applicability");

                    b.HasIndex("ControlId")
                        .IsUnique();

                    b.HasIndex("Domain");

                    b.HasIndex("ImplementationStatus");

                    b.ToTable("Controls");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000000"),
                            Applicability = 0,
                            ControlId = "5.1",
                            ControlName = "Policies for information security",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information security policy and topic-specific policies shall be defined, approved, published, communicated and reviewed.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000000"),
                            Applicability = 0,
                            ControlId = "5.2",
                            ControlName = "Information security roles and responsibilities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information security roles and responsibilities shall be defined and allocated according to the organisation needs.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000000"),
                            Applicability = 0,
                            ControlId = "5.3",
                            ControlName = "Segregation of duties",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conflicting duties and conflicting areas of responsibility shall be segregated.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000000"),
                            Applicability = 0,
                            ControlId = "5.4",
                            ControlName = "Management responsibilities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Management shall require all personnel to apply information security in accordance with the established policy.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000000"),
                            Applicability = 0,
                            ControlId = "5.5",
                            ControlName = "Contact with authorities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall establish and maintain contact with relevant authorities.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000000"),
                            Applicability = 0,
                            ControlId = "5.6",
                            ControlName = "Contact with special interest groups",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall establish and maintain contact with special interest groups.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000000"),
                            Applicability = 0,
                            ControlId = "5.7",
                            ControlName = "Threat intelligence",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information relating to information security threats shall be collected and analysed to produce threat intelligence.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000000"),
                            Applicability = 0,
                            ControlId = "5.8",
                            ControlName = "Information security in project management",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information security shall be integrated into project management.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000000"),
                            Applicability = 0,
                            ControlId = "5.9",
                            ControlName = "Inventory of information and other associated assets",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An inventory of information and other associated assets shall be developed and maintained.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000000"),
                            Applicability = 0,
                            ControlId = "5.10",
                            ControlName = "Acceptable use of information and other associated assets",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rules for the acceptable use and procedures for handling information shall be identified, documented and implemented.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000000"),
                            Applicability = 0,
                            ControlId = "5.11",
                            ControlName = "Return of assets",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personnel and other interested parties shall return all the organisation assets upon change or termination of their employment.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0012-000000000000"),
                            Applicability = 0,
                            ControlId = "5.12",
                            ControlName = "Classification of information",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information shall be classified according to the information security needs of the organisation.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0013-000000000000"),
                            Applicability = 0,
                            ControlId = "5.13",
                            ControlName = "Labelling of information",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An appropriate set of procedures for information labelling shall be developed and implemented.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0014-000000000000"),
                            Applicability = 0,
                            ControlId = "5.14",
                            ControlName = "Information transfer",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0015-000000000000"),
                            Applicability = 0,
                            ControlId = "5.15",
                            ControlName = "Access control",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rules to control physical and logical access to information and other associated assets shall be established and implemented.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000000"),
                            Applicability = 0,
                            ControlId = "5.16",
                            ControlName = "Identity management",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The full life cycle of identities shall be managed.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0017-000000000000"),
                            Applicability = 0,
                            ControlId = "5.17",
                            ControlName = "Authentication information",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Allocation and management of authentication information shall be controlled by a management process.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000000"),
                            Applicability = 0,
                            ControlId = "5.18",
                            ControlName = "Access rights",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 18
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000000"),
                            Applicability = 0,
                            ControlId = "5.19",
                            ControlName = "Information security in supplier relationships",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Processes and procedures shall be defined and implemented to manage information security risks associated with the use of supplier products or services.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 19
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0020-000000000000"),
                            Applicability = 0,
                            ControlId = "5.20",
                            ControlName = "Addressing information security within supplier agreements",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0021-000000000000"),
                            Applicability = 0,
                            ControlId = "5.21",
                            ControlName = "Managing information security in the ICT supply chain",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Processes and procedures shall be defined and implemented to manage information security risks associated with the ICT products and services supply chain.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 21
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0022-000000000000"),
                            Applicability = 0,
                            ControlId = "5.22",
                            ControlName = "Monitoring, review and change management of supplier services",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 22
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0023-000000000000"),
                            Applicability = 0,
                            ControlId = "5.23",
                            ControlName = "Information security for use of cloud services",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organisation information security requirements.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 23
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000000"),
                            Applicability = 0,
                            ControlId = "5.24",
                            ControlName = "Information security incident management planning and preparation",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall plan and prepare for managing information security incidents by defining, establishing and communicating incident management processes.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 24
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0025-000000000000"),
                            Applicability = 0,
                            ControlId = "5.25",
                            ControlName = "Assessment and decision on information security events",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall assess information security events and decide if they are to be categorised as information security incidents.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 25
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000000"),
                            Applicability = 0,
                            ControlId = "5.26",
                            ControlName = "Response to information security incidents",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information security incidents shall be responded to in accordance with the documented procedures.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 26
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0027-000000000000"),
                            Applicability = 0,
                            ControlId = "5.27",
                            ControlName = "Learning from information security incidents",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 27
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0028-000000000000"),
                            Applicability = 0,
                            ControlId = "5.28",
                            ControlName = "Collection of evidence",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 28
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0029-000000000000"),
                            Applicability = 0,
                            ControlId = "5.29",
                            ControlName = "Information security during disruption",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall plan how to maintain information security at an appropriate level during disruption.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 29
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0030-000000000000"),
                            Applicability = 0,
                            ControlId = "5.30",
                            ControlName = "ICT readiness for business continuity",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0031-000000000000"),
                            Applicability = 0,
                            ControlId = "5.31",
                            ControlName = "Legal, statutory, regulatory and contractual requirements",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Legal, statutory, regulatory and contractual requirements relevant to information security and the organisation approach to meet these requirements shall be identified.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 31
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0032-000000000000"),
                            Applicability = 0,
                            ControlId = "5.32",
                            ControlName = "Intellectual property rights",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall implement appropriate procedures to protect intellectual property rights.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 32
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0033-000000000000"),
                            Applicability = 0,
                            ControlId = "5.33",
                            ControlName = "Protection of records",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Records shall be protected from loss, destruction, falsification, unauthorised access and unauthorised release.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 33
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0034-000000000000"),
                            Applicability = 0,
                            ControlId = "5.34",
                            ControlName = "Privacy and protection of PII",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall identify and meet the requirements regarding the preservation of privacy and protection of personally identifiable information.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 34
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0035-000000000000"),
                            Applicability = 0,
                            ControlId = "5.35",
                            ControlName = "Independent review of information security",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation approach to managing information security and its implementation shall be reviewed independently at planned intervals.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 35
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0036-000000000000"),
                            Applicability = 0,
                            ControlId = "5.36",
                            ControlName = "Compliance with policies, rules and standards",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compliance with the organisation information security policy, topic-specific policies, rules and standards shall be regularly reviewed.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 36
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0037-000000000000"),
                            Applicability = 0,
                            ControlId = "5.37",
                            ControlName = "Documented operating procedures",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Operating procedures for information processing facilities shall be documented and made available to personnel who need them.",
                            Domain = 0,
                            ImplementationStatus = 0,
                            SortOrder = 37
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0038-000000000000"),
                            Applicability = 0,
                            ControlId = "6.1",
                            ControlName = "Screening",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Background verification checks on all candidates shall be carried out prior to joining the organisation.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 38
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0039-000000000000"),
                            Applicability = 0,
                            ControlId = "6.2",
                            ControlName = "Terms and conditions of employment",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Employment contractual agreements shall state the personnel and the organisation responsibilities for information security.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 39
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0040-000000000000"),
                            Applicability = 0,
                            ControlId = "6.3",
                            ControlName = "Information security awareness, education and training",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Personnel of the organisation and relevant interested parties shall receive appropriate information security awareness, education and training.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0041-000000000000"),
                            Applicability = 0,
                            ControlId = "6.4",
                            ControlName = "Disciplinary process",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A disciplinary process shall be formalised and communicated to take actions against personnel who have committed an information security policy violation.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 41
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0042-000000000000"),
                            Applicability = 0,
                            ControlId = "6.5",
                            ControlName = "Responsibilities after termination or change of employment",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 42
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0043-000000000000"),
                            Applicability = 0,
                            ControlId = "6.6",
                            ControlName = "Confidentiality or non-disclosure agreements",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Confidentiality or non-disclosure agreements reflecting the organisation needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 43
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0044-000000000000"),
                            Applicability = 0,
                            ControlId = "6.7",
                            ControlName = "Remote working",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organisation premises.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 44
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0045-000000000000"),
                            Applicability = 0,
                            ControlId = "6.8",
                            ControlName = "Information security event reporting",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.",
                            Domain = 1,
                            ImplementationStatus = 0,
                            SortOrder = 45
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0046-000000000000"),
                            Applicability = 0,
                            ControlId = "7.1",
                            ControlName = "Physical security perimeters",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Security perimeters shall be defined and used to protect areas that contain information and other associated assets.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 46
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0047-000000000000"),
                            Applicability = 0,
                            ControlId = "7.2",
                            ControlName = "Physical entry",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secure areas shall be protected by appropriate entry controls and access points.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 47
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0048-000000000000"),
                            Applicability = 0,
                            ControlId = "7.3",
                            ControlName = "Securing offices, rooms and facilities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Physical security for offices, rooms and facilities shall be designed and implemented.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 48
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0049-000000000000"),
                            Applicability = 0,
                            ControlId = "7.4",
                            ControlName = "Physical security monitoring",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premises shall be continuously monitored for unauthorised physical access.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 49
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0050-000000000000"),
                            Applicability = 0,
                            ControlId = "7.5",
                            ControlName = "Protecting against physical and environmental threats",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protection against physical and environmental threats shall be designed and implemented.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0051-000000000000"),
                            Applicability = 0,
                            ControlId = "7.6",
                            ControlName = "Working in secure areas",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Security measures for working in secure areas shall be designed and implemented.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 51
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0052-000000000000"),
                            Applicability = 0,
                            ControlId = "7.7",
                            ControlName = "Clear desk and clear screen",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and enforced.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 52
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0053-000000000000"),
                            Applicability = 0,
                            ControlId = "7.8",
                            ControlName = "Equipment siting and protection",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Equipment shall be sited securely and protected.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 53
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0054-000000000000"),
                            Applicability = 0,
                            ControlId = "7.9",
                            ControlName = "Security of assets off-premises",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Off-site assets shall be protected.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 54
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0055-000000000000"),
                            Applicability = 0,
                            ControlId = "7.10",
                            ControlName = "Storage media",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organisation classification scheme.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 55
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0056-000000000000"),
                            Applicability = 0,
                            ControlId = "7.11",
                            ControlName = "Supporting utilities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 56
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0057-000000000000"),
                            Applicability = 0,
                            ControlId = "7.12",
                            ControlName = "Cabling security",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 57
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0058-000000000000"),
                            Applicability = 0,
                            ControlId = "7.13",
                            ControlName = "Equipment maintenance",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 58
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0059-000000000000"),
                            Applicability = 0,
                            ControlId = "7.14",
                            ControlName = "Secure disposal or re-use of equipment",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten.",
                            Domain = 2,
                            ImplementationStatus = 0,
                            SortOrder = 59
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0060-000000000000"),
                            Applicability = 0,
                            ControlId = "8.1",
                            ControlName = "User endpoint devices",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information stored on, processed by or accessible via user endpoint devices shall be protected.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0061-000000000000"),
                            Applicability = 0,
                            ControlId = "8.2",
                            ControlName = "Privileged access rights",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The allocation and use of privileged access rights shall be restricted and managed.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 61
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0062-000000000000"),
                            Applicability = 0,
                            ControlId = "8.3",
                            ControlName = "Information access restriction",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 62
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0063-000000000000"),
                            Applicability = 0,
                            ControlId = "8.4",
                            ControlName = "Access to source code",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read and write access to source code, development tools and software libraries shall be appropriately managed.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 63
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0064-000000000000"),
                            Applicability = 0,
                            ControlId = "8.5",
                            ControlName = "Secure authentication",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secure authentication technologies and procedures shall be implemented based on information access restrictions and topic-specific policy on access control.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 64
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0065-000000000000"),
                            Applicability = 0,
                            ControlId = "8.6",
                            ControlName = "Capacity management",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 65
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0066-000000000000"),
                            Applicability = 0,
                            ControlId = "8.7",
                            ControlName = "Protection against malware",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protection against malware shall be implemented and supported by appropriate user awareness.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 66
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0067-000000000000"),
                            Applicability = 0,
                            ControlId = "8.8",
                            ControlName = "Management of technical vulnerabilities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information about technical vulnerabilities of information systems in use shall be obtained in a timely fashion to assess the organisation exposure to such vulnerabilities.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 67
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0068-000000000000"),
                            Applicability = 0,
                            ControlId = "8.9",
                            ControlName = "Configuration management",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 68
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0069-000000000000"),
                            Applicability = 0,
                            ControlId = "8.10",
                            ControlName = "Information deletion",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 69
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0070-000000000000"),
                            Applicability = 0,
                            ControlId = "8.11",
                            ControlName = "Data masking",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Data masking shall be used in accordance with the organisation topic-specific policy on access control and other related topic-specific policies.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0071-000000000000"),
                            Applicability = 0,
                            ControlId = "8.12",
                            ControlName = "Data leakage prevention",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 71
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0072-000000000000"),
                            Applicability = 0,
                            ControlId = "8.13",
                            ControlName = "Information backup",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 72
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0073-000000000000"),
                            Applicability = 0,
                            ControlId = "8.14",
                            ControlName = "Redundancy of information processing facilities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 73
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0074-000000000000"),
                            Applicability = 0,
                            ControlId = "8.15",
                            ControlName = "Logging",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 74
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0075-000000000000"),
                            Applicability = 0,
                            ControlId = "8.16",
                            ControlName = "Monitoring activities",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 75
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0076-000000000000"),
                            Applicability = 0,
                            ControlId = "8.17",
                            ControlName = "Clock synchronisation",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The clocks of information processing systems used by the organisation shall be synchronised to approved time sources.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 76
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0077-000000000000"),
                            Applicability = 0,
                            ControlId = "8.18",
                            ControlName = "Use of privileged utility programs",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The use of utility programs that might be capable of overriding system and application controls shall be restricted and tightly controlled.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 77
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0078-000000000000"),
                            Applicability = 0,
                            ControlId = "8.19",
                            ControlName = "Installation of software on operational systems",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Procedures and measures shall be implemented to securely manage software installation on operational systems.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 78
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0079-000000000000"),
                            Applicability = 0,
                            ControlId = "8.20",
                            ControlName = "Networks security",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 79
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0080-000000000000"),
                            Applicability = 0,
                            ControlId = "8.21",
                            ControlName = "Security of network services",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Security mechanisms, service levels and service requirements of all network services shall be identified, implemented and monitored.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 80
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0081-000000000000"),
                            Applicability = 0,
                            ControlId = "8.22",
                            ControlName = "Segregation of networks",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Groups of information services, users and information systems shall be segregated in the organisation networks.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 81
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0082-000000000000"),
                            Applicability = 0,
                            ControlId = "8.23",
                            ControlName = "Web filtering",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Access to external websites shall be managed to reduce exposure to malicious content.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 82
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0083-000000000000"),
                            Applicability = 0,
                            ControlId = "8.24",
                            ControlName = "Use of cryptography",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 83
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0084-000000000000"),
                            Applicability = 0,
                            ControlId = "8.25",
                            ControlName = "Secure development life cycle",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rules for the secure development of software and systems shall be established and applied to developments within the organisation.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 84
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0085-000000000000"),
                            Applicability = 0,
                            ControlId = "8.26",
                            ControlName = "Application security requirements",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Information security requirements shall be identified, specified and approved when developing or acquiring applications.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 85
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0086-000000000000"),
                            Applicability = 0,
                            ControlId = "8.27",
                            ControlName = "Secure system architecture and engineering principles",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 86
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0087-000000000000"),
                            Applicability = 0,
                            ControlId = "8.28",
                            ControlName = "Secure coding",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secure coding principles shall be applied to software development.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 87
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0088-000000000000"),
                            Applicability = 0,
                            ControlId = "8.29",
                            ControlName = "Security testing in development and acceptance",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Security testing processes shall be defined and implemented in the development life cycle.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 88
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0089-000000000000"),
                            Applicability = 0,
                            ControlId = "8.30",
                            ControlName = "Outsourced development",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The organisation shall direct, monitor and review the activities related to outsourced system development.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 89
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0090-000000000000"),
                            Applicability = 0,
                            ControlId = "8.31",
                            ControlName = "Separation of development, test and production environments",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Development, testing and production environments shall be identified and secured.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 90
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0091-000000000000"),
                            Applicability = 0,
                            ControlId = "8.32",
                            ControlName = "Change management",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Changes to information processing facilities and information systems shall be subject to change management procedures.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 91
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0092-000000000000"),
                            Applicability = 0,
                            ControlId = "8.33",
                            ControlName = "Test information",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Test information shall be appropriately selected, protected and managed.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 92
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0093-000000000000"),
                            Applicability = 0,
                            ControlId = "8.34",
                            ControlName = "Protection of information systems during audit testing",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.",
                            Domain = 3,
                            ImplementationStatus = 0,
                            SortOrder = 93
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
