// <auto-generated />
using System;
using GrcPlatform.NonconformityAndCorrectiveActions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrcPlatform.NonconformityAndCorrectiveActions.Infrastructure.Migrations;

[DbContext(typeof(NcDbContext))]
[Migration("20260313000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.HasSequence<int>("NcSequence", "dbo");

        modelBuilder.Entity("GrcPlatform.NonconformityAndCorrectiveActions.Domain.CorrectiveAction", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnType("nvarchar(2000)");

            b.Property<DateTimeOffset>("DueDate")
                .HasColumnType("datetimeoffset");

            b.Property<DateTimeOffset?>("ImplementedAt")
                .HasColumnType("datetimeoffset");

            b.Property<string>("ImplementedByUserId")
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<Guid>("NonconformityId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("OwnerUserId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.HasKey("Id");

            b.HasIndex("NonconformityId");

            b.ToTable("CorrectiveActions");
        });

        modelBuilder.Entity("GrcPlatform.NonconformityAndCorrectiveActions.Domain.Nonconformity", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("ClauseReference")
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(4000)
                .HasColumnType("nvarchar(4000)");

            b.Property<string>("EvidenceReference")
                .HasMaxLength(512)
                .HasColumnType("nvarchar(512)");

            b.Property<DateTimeOffset>("RaisedAt")
                .HasColumnType("datetimeoffset");

            b.Property<string>("RaisedByUserId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)");

            b.Property<string>("ReferenceNumber")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("nvarchar(20)");

            b.Property<string>("Severity")
                .IsRequired()
                .HasMaxLength(16)
                .HasColumnType("nvarchar(16)");

            b.Property<string>("Source")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("nvarchar(40)");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("nvarchar(40)");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("datetimeoffset");

            b.HasKey("Id");

            b.HasIndex("ReferenceNumber")
                .IsUnique();

            b.ToTable("Nonconformities");

            b.OwnsOne("GrcPlatform.NonconformityAndCorrectiveActions.Domain.ValueObjects.EffectivenessReview", "EffectivenessReview", b1 =>
            {
                b1.Property<Guid>("NonconformityId")
                    .HasColumnType("uniqueidentifier");

                b1.Property<bool?>("IsEffective")
                    .HasColumnType("bit")
                    .HasColumnName("Er_IsEffective");

                b1.Property<string>("ReviewNotes")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)")
                    .HasColumnName("Er_ReviewNotes");

                b1.Property<DateTimeOffset?>("ReviewedAt")
                    .HasColumnType("datetimeoffset")
                    .HasColumnName("Er_ReviewedAt");

                b1.Property<string>("ReviewerUserId")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)")
                    .HasColumnName("Er_ReviewerUserId");

                b1.HasKey("NonconformityId");

                b1.ToTable("Nonconformities");

                b1.WithOwner()
                    .HasForeignKey("NonconformityId");
            });

            b.OwnsOne("GrcPlatform.NonconformityAndCorrectiveActions.Domain.ValueObjects.RootCauseAnalysis", "RootCauseAnalysis", b1 =>
            {
                b1.Property<Guid>("NonconformityId")
                    .HasColumnType("uniqueidentifier");

                b1.Property<string>("AnalystUserId")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)")
                    .HasColumnName("Rca_AnalystUserId");

                b1.Property<string>("CauseCategory")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)")
                    .HasColumnName("Rca_CauseCategory");

                b1.Property<string>("CauseDescription")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)")
                    .HasColumnName("Rca_CauseDescription");

                b1.Property<DateTimeOffset?>("CompletedAt")
                    .HasColumnType("datetimeoffset")
                    .HasColumnName("Rca_CompletedAt");

                b1.Property<string>("FiveWhys")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("Rca_FiveWhys");

                b1.Property<string>("Method")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)")
                    .HasColumnName("Rca_Method");

                b1.HasKey("NonconformityId");

                b1.ToTable("Nonconformities");

                b1.WithOwner()
                    .HasForeignKey("NonconformityId");
            });

            b.Navigation("EffectivenessReview");
            b.Navigation("RootCauseAnalysis");
        });

        modelBuilder.Entity("GrcPlatform.NonconformityAndCorrectiveActions.Domain.CorrectiveAction", b =>
        {
            b.HasOne("GrcPlatform.NonconformityAndCorrectiveActions.Domain.Nonconformity", null)
                .WithMany("CorrectiveActions")
                .HasForeignKey("NonconformityId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("GrcPlatform.NonconformityAndCorrectiveActions.Domain.Nonconformity", b =>
        {
            b.Navigation("CorrectiveActions");
        });
#pragma warning restore 612, 618
    }
}
