// <auto-generated />
using System;
using GrcPlatform.IncidentManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GrcPlatform.IncidentManagement.Infrastructure.Migrations;

[DbContext(typeof(IncidentDbContext))]
[Migration("20260319000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11")
                    .HasAnnotation("Relational:MaxIdentifierLength", 128);
        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        modelBuilder.HasSequence<int>("IncidentSequence", "dbo");

        modelBuilder.Entity("GrcPlatform.IncidentManagement.Domain.Incident", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<string>("ReferenceNumber").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Severity").IsRequired().HasMaxLength(16).HasColumnType("nvarchar(16)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Description").IsRequired().HasMaxLength(4000).HasColumnType("nvarchar(4000)");
            b.Property<string>("ImpactDescription").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<DateTimeOffset>("OccurredAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("DetectedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("ContainedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("ResolvedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("ClosedAt").HasColumnType("datetimeoffset");
            b.Property<string>("ReportedByUserId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("AssignedToUserId").HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("CustomerId").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("CustomerName").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("LinkedControlId").HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("AffectedAssetIds").HasColumnType("nvarchar(max)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("datetimeoffset");
            b.HasKey("Id");
            b.HasIndex("ReferenceNumber").IsUnique();
            b.HasIndex("Status");
            b.HasIndex("Severity");
            b.HasIndex("CustomerId");
            b.ToTable("Incidents");

            b.OwnsOne("GrcPlatform.IncidentManagement.Domain.PostIncidentReview", "PostIncidentReview", b1 =>
            {
                b1.Property<Guid>("IncidentId").HasColumnType("uniqueidentifier");
                b1.Property<string>("Summary").HasMaxLength(2000).HasColumnType("nvarchar(2000)").HasColumnName("Pir_Summary");
                b1.Property<string>("RootCause").HasMaxLength(2000).HasColumnType("nvarchar(2000)").HasColumnName("Pir_RootCause");
                b1.Property<string>("LessonsLearned").HasMaxLength(2000).HasColumnType("nvarchar(2000)").HasColumnName("Pir_LessonsLearned");
                b1.Property<string>("Recommendations").HasMaxLength(2000).HasColumnType("nvarchar(2000)").HasColumnName("Pir_Recommendations");
                b1.Property<string>("ReviewerUserId").HasMaxLength(128).HasColumnType("nvarchar(128)").HasColumnName("Pir_ReviewerUserId");
                b1.Property<DateTimeOffset?>("ReviewedAt").HasColumnType("datetimeoffset").HasColumnName("Pir_ReviewedAt");
                b1.HasKey("IncidentId");
                b1.ToTable("Incidents");
                b1.WithOwner().HasForeignKey("IncidentId");
            });

            b.Navigation("PostIncidentReview");
        });

        modelBuilder.Entity("GrcPlatform.IncidentManagement.Domain.IncidentAction", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<Guid>("IncidentId").HasColumnType("uniqueidentifier");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<string>("AssignedToUserId").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTimeOffset?>("DueDate").HasColumnType("datetimeoffset");
            b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("datetimeoffset");
            b.Property<string>("CompletedByUserId").HasMaxLength(128).HasColumnType("nvarchar(128)");
            b.Property<string>("Notes").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.HasKey("Id");
            b.HasIndex("IncidentId");
            b.ToTable("IncidentActions");
            b.HasOne("GrcPlatform.IncidentManagement.Domain.Incident", null)
             .WithMany("Actions").HasForeignKey("IncidentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("GrcPlatform.IncidentManagement.Domain.Incident", b =>
        {
            b.Navigation("Actions");
        });
#pragma warning restore 612, 618
    }
}
